name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check if on main branch
        run: |
          if [ "${GITHUB_REF##*/}" != "main" ]; then
            echo "Not on main branch, exiting..."
            exit 0
          fi
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
      - name: Archive production artifacts
        run: |
          zip -r react-common.zip src/react-common
      - name: check folder structure
        run: |
      - name: concatenate version number to tar file
        env:
          tag: ${{ github.ref_name }}
        #         echo "// $tag \n" >> temp.txt
        run: |
          cat react-common.zip  >> temp.txt
          mv temp.txt react-common.zip
      - name: Add artifacts to the release 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload "$tag" react-common.zip --clobber

